### ISSUE TITLE
Cannot run REMESH.f

### ISSUE THREAD

**Issue by DitJee** [DitJee/adaptive-mesh#4]
I was found that when using `gfortran REMESH.f -std=legacy` to run the code. The compiler threw this error

![image](https://user-images.githubusercontent.com/56587469/129138486-b1e2d5a0-9c2e-4c5c-b05d-77547643387f.png)

**Comment by bilbo290** [comment]
Issue solved with the latest REMESH.f script, possibly cleaned and built via SimplyFortran2. The built executable run as intended now.
